### ISSUE TITLE
Rogue Elusive Passive Issue

### ISSUE THREAD

**Issue by KittenIsLive** [DevsCube-Official/AETERNUM#1]
Whenever I equip rogue's "Elusive" passive ability onto a wheel slot, my chat gets spammed with "[Aeternum] A cooldown is active for this ability!"

**Comment by SwitchedCube** [comment]
Managed to reproduce this issue. I'll look into what might cause it

**Comment by SwitchedCube** [comment]
mb, I accidentally added elusive as a passive ability in the [spreadsheet with all the abilities](https://tinyurl.com/aeternum-abilities). Whoopsie daisy, lmao. I fixed it now.
