### ISSUE TITLE
Ability shown as used and on cooldown

### ISSUE THREAD

**Issue by KittenIsLive** [DevsCube-Official/AETERNUM#2]
![image](https://github.com/user-attachments/assets/2a3a0f05-c39b-4292-b287-195edc682cdd)

All abilities I'm using are showing as both being activated and being on cooldown when trying to use them on cooldown. When not on cooldown it functions normally. This wasn't always happening, only started happening recently.

**Comment by SwitchedCube** [comment]
the problem only occurs with ring of fire and lumos, correct?

**Comment by KittenIsLive** [comment]
> the problem only occurs with ring of fire and lumos, correct?

Actually, it seems to happen with most if not all of the abilities I use.

**Comment by KittenIsLive** [comment]
Can confirm that it's happening with Lumos, Ring of Fire, Night's Eye, and Cloak.
Can't test more as I don't have more unlocked.

**Comment by SwitchedCube** [comment]
so the problem is that it says "Ring of Fire Activated" and then ALSO says "A cooldown is active" right?

no other problems??

**Comment by KittenIsLive** [comment]
> so the problem is that it says "Ring of Fire Activated" and then ALSO says "A cooldown is active" right?

Correct, everything still functions fine, but whenever I use the skill **while it is on cooldown**, it both says that the skill has been used (which it just shouldn't say), and that it is on cooldown (which it is).

**Comment by SwitchedCube** [comment]
ah, i see. looks like i messed up somewhere and it showed the message even after cooldown. I'll fix it lmfao

**Comment by SwitchedCube** [comment]
fixed.
